### ISSUE TITLE
Please add a license to this project

### ISSUE THREAD

**Issue by jbcpollak** [hgwood/java8-streams-and-exceptions#1]
Hello,

I found your project and I think the concepts are really useful. Could you add a license to the repository so its clear if we could use your code directly, or as a library, etc?

Do you know of other similar implementations?

**Comment by hgwood** [comment]
Thanks for your interest! I've added a LICENCE file (MIT). A colleague of mine has worked on something similar. You can find his code [here](https://github.com/Zenika/Try).

I'd be glad to hear what you'll do with it. :)

**Comment by jbcpollak** [comment]
Thanks!
